export const COMPLETE_MENU = [
	{
		typeOf: "appetizers",
		title: "kimchi",
		description: "jabłko/sezam/arbuz",
		price: "15zł",
		photo: "",
		vege: true,
	},
	{
		typeOf: "appetizers",
		title: "wołowina tataki",
		description: "yuzu/furikake/czerwona cebula/orzech laskowy",
		price: "42zł",
		photo: "",
		vege: false,
	},
	{
		typeOf: "appetizers",
		title: "smażone krewetki 8 pcs.",
		description: "marynowany imbir/chilli/ogórek/awokado",
		price: "39zł",
		photo: "",
		vege: false,
	},
	{
		typeOf: "appetizers",
		title: "edamame",
		description: "chilli,tofu,kolendra",
		price: "23zł",
		photo: "",
		vege: true,
	},
	{
		typeOf: "ramen",
		title: "ramen yakitori",
		description:
			"grilowany kurczak/jajko/sezam/grilowana kukurydza/dymka/por/nori",
		price: "33zł",
		photo: "",
		vege: false,
	},
	{
		typeOf: "ramen",
		title: "ramen tantamen",
		description: "żeberka/pak choy/dymka/ragu wieprzowe/jajko",
		price: "35zł",
		photo: "",
		vege: false,
	},
	{
		typeOf: "ramen",
		title: "ramen yakiniku",
		description:
			"wołowina/krewetki/kiełki fasoli/nori/prażony sezam/dymka/dashi",
		price: "43zł",
		photo: "",
		vege: false,
	},
	{
		typeOf: "ramen",
		title: "ramen kotteri",
		description:
			"grzyby/pieczony bakłażan/szpinak/kukurydza + opcjonalnie jajko",
		price: "41zł",
		photo: "",
		vege: true,
	},
	{
		typeOf: "udon",
		title: "udon z wołowiną",
		description: "zielone warzywa/grzyby/sos teryaki/szosnek/jajko",
		price: "39zł",
		photo: "",
		vege: false,
	},
	{
		typeOf: "udon",
		title: "udon z krewetkami/wege",
		description:
			"warzywa/marynowany imbir/glony/sos ostrygowy/sezam/dymka/chilli/sos kokosowy/trawa cytrynowa",
		price: "39zł",
		photo: "",
		vege: true,
	},
	{
		typeOf: "main_course",
		title: "żeberka z sosem teryaki",
		description: "okonomiyaki z chashu/marynowane ogórki",
		price: "53zł",
		photo: "",
		vege: false,
	},
	{
		typeOf: "main_course",
		title: "smażony stek z kalmara",
		description: "zielona fasolka/sezam/katsobushi/okonomiyaki z warzywami",
		price: "49zł",
		photo: "",
		vege: false,
	},
	{
		typeOf: "dessert",
		title: "lody yuzu z ciasteczkiem migdałowym i musem jabłkowym",
		description: null,
		price: "19zł",
		photo: "",
		vege: null,
	},
	{
		typeOf: "dessert",
		title: "krem matcha z wanillią",
		description: null,
		price: "15zł",
		photo: "",
		vege: null,
	},
];
